version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: askme_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: askme
      POSTGRES_PASSWORD: askme_pass
      POSTGRES_DB: askme_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/01_init.sql

volumes:
  pgdata:
